### ISSUE TITLE
Flakey Test: `createAndStartPublisherAndSubscriberAndWaitUntilDataEnds` (`PublisherAndSubscriberTests`)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#259]
Observed when running `emulate` workflow on #243.

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: Expectation 'track response' unfulfilled.
	at com.ably.tracking.test.common.Expectation.assertFulfilled(Expectations.kt:55)
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-789) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
This should be fixed after landing https://github.com/ably/ably-asset-tracking-android/pull/428

**Comment by QuintinWillison** [comment]
[At API Level 21](https://github.com/ably/ably-asset-tracking-android/actions/runs/3716720723/jobs/6303356761#step:4:779) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 3) expected:<com.ably.tracking.EnhancedLocationUpdate@bc797d73> but was:<com.ably.tracking.EnhancedLocationUpdate@be4f8529>
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3730953632/jobs/6329036149#step:4:919) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 3) expected:<com.ably.tracking.EnhancedLocationUpdate@b407d20d> but was:<com.ably.tracking.EnhancedLocationUpdate@b63766de>
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3750116593/jobs/6369409219#step:4:865) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 3) expected:<com.ably.tracking.EnhancedLocationUpdate@55ec75a8> but was:<com.ably.tracking.EnhancedLocationUpdate@57c208ff>
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 24](https://github.com/ably/ably-asset-tracking-android/actions/runs/3758792954/jobs/6387563439#step:4:855) (for `main` branch):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 3) expected:<com.ably.tracking.EnhancedLocationUpdate@1485194a> but was:<com.ably.tracking.EnhancedLocationUpdate@164137d9>
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 21](https://github.com/ably/ably-asset-tracking-android/actions/runs/3846018621/jobs/6550833354#step:4:851) (https://github.com/ably/ably-asset-tracking-android/pull/880):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 5) expected:<com.ably.tracking.EnhancedLocationUpdate@596741d4> but was:<com.ably.tracking.EnhancedLocationUpdate@5b22ec04>
	at org.junit.Assert.fail(Assert.java:89)
Tests on test(AVD) - 5.0.2 failed: There was 1 failure(s).

> Task :integration-testing-app:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.
```

**Comment by QuintinWillison** [comment]
[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3874455099/jobs/6605675067#step:4:1011) (https://github.com/ably/ably-asset-tracking-android/pull/884):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > createAndStartPublisherAndSubscriberAndWaitUntilDataEnds[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Received Subscriber location should be equal to published Publisher location (index 3) expected:<com.ably.tracking.EnhancedLocationUpdate@88088755> but was:<com.ably.tracking.EnhancedLocationUpdate@89d2bd65>
	at org.junit.Assert.fail(Assert.java:89)
```
