### ISSUE TITLE
When an invalid Ably key is used when building an example app there is no log message explaining what is not working

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#335]
There should be a log message showing that API key is incorrect. 

Probably related to https://github.com/ably/ably-asset-tracking-android/issues/326

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-856) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
After landing the simple logger PR and particularly by adding [this](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/Ably.kt#L174) log handler to the Ably SDK any error message from Ably will be forwarded to the handler. I've run the app with an invalid key and this is the error log that I've received.
```
io.ably.lib.types.AblyException: java.lang.Exception: Invalid key specified
        at io.ably.lib.rest.Auth.createTokenRequest(Auth.java:720)
        at io.ably.lib.rest.Auth.requestToken(Auth.java:674)
        at io.ably.lib.rest.Auth.assertValidToken(Auth.java:959)
        at io.ably.lib.rest.Auth.assertValidToken(Auth.java:943)
        at io.ably.lib.rest.Auth.getAuthParams(Auth.java:808)
        at io.ably.lib.transport.WebSocketTransport.connect(WebSocketTransport.java:63)
        at io.ably.lib.transport.ConnectionManager.connectImpl(ConnectionManager.java:1359)
        at io.ably.lib.transport.ConnectionManager.access$400(ConnectionManager.java:30)
        at io.ably.lib.transport.ConnectionManager$Connecting.enact(ConnectionManager.java:216)
        at io.ably.lib.transport.ConnectionManager$StateChangeAction.enactState(ConnectionManager.java:551)
        at io.ably.lib.transport.ConnectionManager$AsynchronousStateChangeAction.run(ConnectionManager.java:595)
        at io.ably.lib.transport.ConnectionManager$ActionHandler.run(ConnectionManager.java:705)
        at java.lang.Thread.run(Thread.java:761)
```
So I guess that this issue could be closed :wink:

**Comment by kavalerov** [comment]
You are right, looks like this got resolved 👍
