### ISSUE TITLE
Publishing app crashes on Android API 21

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#359]
When running the publisher example app on an Android 21 emulator the app is crashing in at least two places:
1. When starting the app it crashes because the new Ably logo is using a [gradient](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-example-app/src/main/res/drawable/header_logo_with_title.xml#L52). After removing that gradient everything works.
2. When starting the publisher service the app crashes with an error connected to notification, probably something is wrong with the icon.
```
06-02 13:26:24.105 10832-10832/com.ably.tracking.example.publisher E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ably.tracking.example.publisher, PID: 10832
    android.app.RemoteServiceException: Bad notification posted from package com.ably.tracking.example.publisher: Couldn't create icon: StatusBarIcon(pkg=com.ably.tracking.example.publisheruser=0 id=0x7f070086 level=0 visible=true num=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-909) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We've decided that the appropriate fix for this is to increase the Android runtime API Level requirement to 24 for the example apps.

Under a separate issue we will ensure we test API Level 21 under emulation. I'll create that issue shortly.

**Comment by QuintinWillison** [comment]
https://github.com/ably/ably-asset-tracking-android/issues/378
