### ISSUE TITLE
ConnectionException after waking up a device with subscriber running

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-asset-tracking-android#702]
SDK throws an exception when waking up a device after it went to sleep on a screen that was subscribing to trackable updates.

Steps:
1. Run an activity with subscribers listening to updates on a trackable
2. Lock the device
3. Wait for the app process to stop (doze mode kicks in?)
4. Unlock the device
5. App crashes due to `ConnectionException: Unable to enter presence channel in detached or failed state`

In my tests, it took a few minutes for the app to be stopped when not charging, could not reproduce the issues when the phone was connected to a charger.

Here are the app logs since it resumed
```
2022-06-24 13:57:19.107 24186-24563/com.ably.tracking.demo.subscriber D/AssetTracker: Message: 24-06-22 13:57:19.106: io.ably.lib.transport.WebSocketTransport: onClose(): wsCode = 1006; wsReason = ; remote = true, Throwable: null
2022-06-24 13:57:19.121 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.120: io.ably.lib.http.HttpCore: HTTP request: https://internet-up.ably-realtime.com/is-the-internet-up.txt GET, Throwable: null
2022-06-24 13:57:19.127 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.122: io.ably.lib.http.HttpCore:   Ably-Agent: ably-java/1.2.12 ably-asset-tracking-android/1.1.0-rc.4 android/31, Throwable: null
2022-06-24 13:57:19.130 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.128: io.ably.lib.http.HttpCore:   Accept: application/json, Throwable: null
2022-06-24 13:57:19.132 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.130: io.ably.lib.http.HttpCore:   X-Ably-Version: 1.2, Throwable: null
2022-06-24 13:57:19.181 24186-24563/com.ably.tracking.demo.subscriber W/System.err: java.net.UnknownHostException: Unable to resolve host "internet-up.ably-realtime.com": No address associated with hostname
2022-06-24 13:57:19.182 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
2022-06-24 13:57:19.182 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
2022-06-24 13:57:19.182 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
2022-06-24 13:57:19.182 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:41)
2022-06-24 13:57:19.182 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2022-06-24 13:57:19.183 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpCore.readResponse(HttpCore.java:402)
2022-06-24 13:57:19.184 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:259)
2022-06-24 13:57:19.185 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:166)
2022-06-24 13:57:19.185 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpCore.httpExecuteWithRetry(HttpCore.java:84)
2022-06-24 13:57:19.185 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpHelpers.httpExecute(HttpHelpers.java:108)
2022-06-24 13:57:19.185 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpHelpers.getUrl(HttpHelpers.java:57)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.http.HttpHelpers.getUrlString(HttpHelpers.java:45)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.transport.ConnectionManager.checkConnectivity(ConnectionManager.java:1427)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.transport.ConnectionManager.checkFallback(ConnectionManager.java:1236)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.transport.ConnectionManager.onTransportUnavailable(ConnectionManager.java:1312)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at io.ably.lib.transport.WebSocketTransport$WsClient.onClose(WebSocketTransport.java:227)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:526)
2022-06-24 13:57:19.186 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:524)
2022-06-24 13:57:19.187 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:536)
2022-06-24 13:57:19.195 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:585)
2022-06-24 13:57:19.195 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.client.WebSocketClient.handleIOException(WebSocketClient.java:822)
2022-06-24 13:57:19.195 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:429)
2022-06-24 13:57:19.196 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at java.lang.Thread.run(Thread.java:920)
2022-06-24 13:57:19.203 24186-24563/com.ably.tracking.demo.subscriber W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
2022-06-24 13:57:19.204 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at libcore.io.Linux.android_getaddrinfo(Native Method)
2022-06-24 13:57:19.204 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
2022-06-24 13:57:19.205 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
2022-06-24 13:57:19.205 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
2022-06-24 13:57:19.205 24186-24563/com.ably.tracking.demo.subscriber W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
2022-06-24 13:57:19.205 24186-24563/com.ably.tracking.demo.subscriber W/System.err: 	... 34 more
2022-06-24 13:57:19.213 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.208: io.ably.lib.transport.ConnectionManager: checkSuspended: timeToSuspend = -38916ms; suspendMode = true, Throwable: null
2022-06-24 13:57:19.217 24186-24563/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.214: io.ably.lib.transport.ConnectionManager: setState(): setting suspended; reason {ErrorInfo message=Connection temporarily unavailable (See https://help.ably.io/error/80003) code=80003 statusCode=503 href=https://help.ably.io/error/80003}, Throwable: null
2022-06-24 13:57:19.233 24186-24560/com.ably.tracking.demo.subscriber D/AssetTracker: Message: 24-06-22 13:57:19.218: io.ably.lib.transport.ConnectionManager: Wait ended by action: io.ably.lib.transport.ConnectionManager$SynchronousStateChangeAction@81c8ab1, Throwable: null
2022-06-24 13:57:19.241 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: handleAppVisibility mAppVisible=false visible=true
2022-06-24 13:57:19.244 24186-24560/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.235: io.ably.lib.realtime.Channel: setSuspended(); channel = tracking:Pizza, Throwable: null
2022-06-24 13:57:19.246 24186-24560/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.245: io.ably.lib.realtime.Channel: failQueuedMessages(), Throwable: null
2022-06-24 13:57:19.247 24186-24560/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.246: io.ably.lib.realtime.Channel: setState(): channel = tracking:Pizza; setting suspended, Throwable: null
2022-06-24 13:57:19.249 24186-24560/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.248: io.ably.lib.realtime.Channel: failQueuedMessages(), Throwable: null
2022-06-24 13:57:19.252 24186-24360/com.ably.tracking.demo.subscriber D/OpenGLRenderer: setSurface called with nullptr
2022-06-24 13:57:19.285 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)4 dur=30 res=0x1 s={false 0} ch=false fn=-1
2022-06-24 13:57:19.302 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: stopped(false) old=true
2022-06-24 13:57:19.321 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: stopped(false) old=false
2022-06-24 13:57:19.334 24186-24186/com.ably.tracking.demo.subscriber D/AssetTracker: Setting foreground resolution
2022-06-24 13:57:19.336 24186-24186/com.ably.tracking.demo.subscriber I/DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
2022-06-24 13:57:19.348 24186-24557/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.336: io.ably.lib.realtime.Channel: update(); channel = tracking:Pizza, Throwable: null
2022-06-24 13:57:19.363 24186-24557/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.348: io.ably.lib.realtime.Channel: update(); channel = tracking:Pizza, Throwable: null
2022-06-24 13:57:19.415 24186-24360/com.ably.tracking.demo.subscriber D/OpenGLRenderer: setSurface called with nullptr
2022-06-24 13:57:19.456 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=9 res=0x7 s={true 482797022672} ch=true fn=-1
2022-06-24 13:57:19.462 24186-24360/com.ably.tracking.demo.subscriber D/OpenGLRenderer: eglCreateWindowSurface
2022-06-24 13:57:19.490 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11387 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
2022-06-24 13:57:19.516 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2022-06-24 13:57:19.516 24186-24186/com.ably.tracking.demo.subscriber I/ViewRootImpl@9476f94[MainActivity]: [DP] rdf()
2022-06-24 13:57:19.516 24186-24186/com.ably.tracking.demo.subscriber D/ViewRootImpl@9476f94[MainActivity]: reportDrawFinished (fn: -1) 
2022-06-24 13:57:21.008 25329-25329/com.ably.tracking.demo.subscriber D/ActivityThread: handleBindApplication()++ app=com.ably.tracking.demo.subscriber
2022-06-24 13:57:19.955 24186-24186/com.ably.tracking.demo.subscriber E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ably.tracking.demo.subscriber, PID: 24186
    com.ably.tracking.ConnectionException: Unable to enter presence channel in detached or failed state
        at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:55)
        at com.ably.tracking.common.DefaultAbly.updatePresenceData(Ably.kt:583)
        at com.ably.tracking.common.DefaultAbly.access$updatePresenceData(Ably.kt:204)
        at com.ably.tracking.common.DefaultAbly$updatePresenceData$1$1.invokeSuspend(Ably.kt:558)
        at com.ably.tracking.common.DefaultAbly$updatePresenceData$1$1.invoke(Unknown Source:8)
        at com.ably.tracking.common.DefaultAbly$updatePresenceData$1$1.invoke(Unknown Source:4)
        at com.ably.tracking.common.DefaultAbly.retryChannelOperationIfConnectionResumeFails(Ably.kt:625)
        at com.ably.tracking.common.DefaultAbly.access$retryChannelOperationIfConnectionResumeFails(Ably.kt:204)
        at com.ably.tracking.common.DefaultAbly$updatePresenceData$1.invokeSuspend(Ably.kt:557)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9031a69, Dispatchers.Main.immediate]
2022-06-24 13:57:19.996 24186-24186/com.ably.tracking.demo.subscriber I/Process: Sending signal. PID: 24186 SIG: 9
2022-06-24 13:57:20.954 25329-25329/? I/demo.subscribe: Late-enabling -Xcheck:jni
2022-06-24 13:57:20.981 25329-25329/? E/USNET: USNET: appName: com.ably.tracking.demo.subscriber
2022-06-24 13:57:20.986 25329-25329/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-06-24 13:57:20.991 25329-25329/? D/ActivityThread: setConscryptValidator
2022-06-24 13:57:20.991 25329-25329/? D/ActivityThread: setConscryptValidator - put
2022-06-24 13:57:21.009 25329-25329/com.ably.tracking.demo.subscriber D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10728; state: ENABLED
2022-06-24 13:57:21.271 25329-25329/com.ably.tracking.demo.subscriber V/GraphicsEnvironment: ANGLE Developer option for 'com.ably.tracking.demo.subscriber' set to: 'default'
2022-06-24 13:57:21.271 25329-25329/com.ably.tracking.demo.subscriber V/GraphicsEnvironment: App is not on the allowlist for updatable production driver.
2022-06-24 13:57:21.274 25329-25329/com.ably.tracking.demo.subscriber D/LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.ably.tracking.demo.subscriber appContext.mBasePackageName=com.ably.tracking.demo.subscriber
2022-06-24 13:57:21.274 25329-25329/com.ably.tracking.demo.subscriber D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-06-24 13:57:21.293 25329-25329/com.ably.tracking.demo.subscriber D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-06-24 13:57:21.312 25329-25329/com.ably.tracking.demo.subscriber I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2022-06-24 13:57:21.318 25329-25329/com.ably.tracking.demo.subscriber I/FirebaseCrashlytics: Initializing Firebase Crashlytics 18.2.11 for com.ably.tracking.demo.subscriber
2022-06-24 13:57:21.378 25329-25329/com.ably.tracking.demo.subscriber I/FirebaseInitProvider: FirebaseApp initialization successful
2022-06-24 13:57:21.390 25329-25329/com.ably.tracking.demo.subscriber D/ActivityThread: handleBindApplication() --
2022-06-24 13:57:21.497 25329-25360/com.ably.tracking.demo.subscriber I/TRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
2022-06-24 13:57:23.602 25329-25360/com.ably.tracking.demo.subscriber I/TRuntime.CctTransportBackend: Status Code: 200
2022-06-24 13:57:26.651 25329-25382/com.ably.tracking.demo.subscriber D/ProfileInstaller: Installing profile for com.ably.tracking.demo.subscriber

```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2110) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
The issue occurs because the channel goes into the `suspended` state as you can see here:
```
2022-06-24 13:57:19.247 24186-24560/com.ably.tracking.demo.subscriber V/AssetTracker: Message: 24-06-22 13:57:19.246: io.ably.lib.realtime.Channel: setState(): channel = tracking:Pizza; setting suspended, Throwable: null
```
then when a presence call happens the [`ably-android` throws an error](https://github.com/ably/ably-java/blob/07f4c9b8f1fd2b63d5d7ca234f16bc9803546fc4/lib/src/main/java/io/ably/lib/realtime/Presence.java#L634) due to the channel being in a wrong state.

The `suspended` state is described as 
```
The Channel, having previously been attached, has lost continuity, usually due to the 
client being disconnected from Ably for more than two minutes. It will automatically 
attempt to reattach as soon as connectivity is restored.
```
so this makes me wonder whether the AAT should simply wait for the automatic reattach or should we explicitly call the `attach()` method and wait for it to complete? WDYT @QuintinWillison ? :thinking:
