### ISSUE TITLE
ConnectionException on timeout when starting subscription

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-asset-tracking-android#706]
SDK throws an exception when subscribing to a channel fails.
I couldn't find a place to add an error handler

```
--------- beginning of crash
2022-07-05 12:51:21.646 29757-29757/com.ably.tracking.demo.subscriber E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ably.tracking.demo.subscriber, PID: 29757
java.lang.Exception: com.ably.tracking.ConnectionException: Attach timed out for channel tracking:pizza
at com.ably.tracking.common.DefaultAbly$connect$1$1.onError(Ably.kt:292)
at io.ably.lib.realtime.Presence.failQueuedMessages(Presence.java:728)
at io.ably.lib.realtime.Presence.setSuspended(Presence.java:780)
at io.ably.lib.realtime.ChannelBase.setSuspended(ChannelBase.java:562)
at io.ably.lib.realtime.ChannelBase$2.run(ChannelBase.java:408)
at java.util.TimerThread.mainLoop(Timer.java:562)
at java.util.TimerThread.run(Timer.java:512)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@62bc34a, Dispatchers.Main.immediate]
Caused by: com.ably.tracking.ConnectionException: Attach timed out for channel tracking:pizza
at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:55)
... 7 more
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2396) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
Upon further investigation it turned out this exception is thrown directly by `start()` method in subscriber and can be simply caught
