### ISSUE TITLE
Fix crash when publisher tries to modify its internal state after being stopped

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#808]
We've seen a fatal exception occur when using the publisher SDK. It looks like the publisher is stopped but then it itself tries to access its own state which leads to the `PublisherPropertiesDisposedException` being thrown. This should not happen as after stopping the publisher should perform no operations on its own.

```
Fatal Exception: w3.i0: Cannot access the publisher properties after it's disposed.
       at com.ably.tracking.publisher.DefaultCorePublisher$Properties.getTrackableStateFlows(CorePublisher.kt:700)
       at com.ably.tracking.publisher.DefaultCorePublisher$updateTrackableState$1.invokeSuspend(CorePublisher.kt:475)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by ikbalkaya** [comment]
Just a question on this, Is there  a mechanism that prevents use of disposed properties? If not I suppose that might be a race condition issue where trackableStateflows still emits updates after it was stopped. I will investigate the potential of this happening

**Comment by KacperKluka** [comment]
The mechanism you mention is the error throwing that happens 😉 When you try to access disposed properties they will throw the `PublisherPropertiesDisposedException`
