### ISSUE TITLE
`staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber` (`AuthenticationTests`) failing with "Expectation 'subscriber received a location update' unfulfilled."

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#844]
Seems to pass on the majority (over 50%) of test runs, therefore looks like it's flakey.

Failing from our Android emulation workflow. These links will only survive as long as GitHub keeps the test run logs, so I'll also quote from the output...

[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3684425848/jobs/6235398967#step:4:1015) (https://github.com/ably/ably-asset-tracking-android/pull/841):

```
com.ably.tracking.tests.AuthenticationTests > staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Expectation 'subscriber received a location update' unfulfilled.
	at com.ably.tracking.test.android.common.Expectation.assertFulfilled(Expectations.kt:55)
Tests on test(AVD) - 10 failed: There was 1 failure(s).

> Task :integration-testing-app:connectedDebugAndroidTest FAILED
```

[At API Level 24](https://github.com/ably/ably-asset-tracking-android/actions/runs/3685077251/jobs/6235588965#step:4:956) (https://github.com/ably/ably-asset-tracking-android/pull/842):

```
com.ably.tracking.tests.AuthenticationTests > staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: Expectation 'subscriber received a location update' unfulfilled.
	at com.ably.tracking.test.android.common.Expectation.assertFulfilled(Expectations.kt:55)
```

[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3685230365/jobs/6235939378#step:4:1090) (https://github.com/ably/ably-asset-tracking-android/pull/843):

```
com.ably.tracking.tests.AuthenticationTests > staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Expectation 'subscriber received a location update' unfulfilled.
	at com.ably.tracking.test.android.common.Expectation.assertFulfilled(Expectations.kt:55)
Tests on test(AVD) - 10 failed: There was 1 failure(s).
```

**Comment by QuintinWillison** [comment]
[At API Level 24](https://github.com/ably/ably-asset-tracking-android/pull/855) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.tests.AuthenticationTests > staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: Expectation 'subscriber received a location update' unfulfilled.
	at com.ably.tracking.test.android.common.Expectation.assertFulfilled(Expectations.kt:55)
```

**Comment by QuintinWillison** [comment]
[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3730953632/jobs/6328603478#step:4:924) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.tests.AuthenticationTests > staticTokenAuthenticationShouldCreateWorkingConnectionBetweenPublisherAndSubscriber[test(AVD) - 10] FAILED 
	java.lang.AssertionError: Expectation 'subscriber received a location update' unfulfilled.
	at com.ably.tracking.test.android.common.Expectation.assertFulfilled(Expectations.kt:55)
```

**Comment by QuintinWillison** [comment]
I'm not going to link to the failure runs again as this issue is already noisy enough with commentary, but I just had this test fail 2 (out of 2!) CI check job re-runs. This test is a major blocker to PR velocity.
