### ISSUE TITLE
`shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart` (`PublisherAndSubscriberTests`) failing with "first publisherPresence value should be true"

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#845]
I've only seen one failure so far for this test, but am creating an issue so we can track it.

Failing from our Android emulation workflow. This link will only survive as long as GitHub keeps the test run logs, so I'll also quote from the output...

[At API Level 24](https://github.com/ably/ably-asset-tracking-android/actions/runs/3685077251/jobs/6235588965#step:4:960) (https://github.com/ably/ably-asset-tracking-android/pull/842):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError: first publisherPresence value should be true
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 21](https://github.com/ably/ably-asset-tracking-android/actions/runs/3758334740/jobs/6386549727#step:4:858) (https://github.com/ably/ably-asset-tracking-android/pull/856):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError: first publisherPresence value should be true
	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by QuintinWillison** [comment]
[At API Level 21](https://github.com/ably/ably-asset-tracking-android/actions/runs/3846090573/jobs/6550991350#step:4:732):

```
com.ably.tracking.tests.PublisherAndSubscriberTests > shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError: first publisherPresence value should be true
	at org.junit.Assert.fail(Assert.java:89)
Tests on test(AVD) - 5.0.2 failed: There was 1 failure(s).

> Task :integration-testing-app:connectedDebugAndroidTest FAILED
```

**Comment by QuintinWillison** [comment]
While working locally on #259 I had this test fail when I ran this group of tests.

I used `./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.ably.tracking.tests.PublisherAndSubscriberTests :integration-testing-app:connectedDebugAndroidTest` and got:

```
com.ably.tracking.tests.PublisherAndSubscriberTests > shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart[Nexus_S_API_22(AVD) - 5.1.1] FAILED
        java.lang.AssertionError: first publisherPresence value should be true
        at org.junit.Assert.fail(Assert.java:89)
Tests on Nexus_S_API_22(AVD) - 5.1.1 failed: There was 1 failure(s).

> Task :integration-testing-app:connectedDebugAndroidTest FAILED
```

Where a bit more detail was present in the report:

```
java.lang.AssertionError: first publisherPresence value should be true
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at com.ably.tracking.tests.PublisherAndSubscriberTests.shouldNotEmitPublisherPresenceFalseIfPublisherIsPresentFromTheStart(PublisherAndSubscriberTests.kt:294)
```

at (`git rev-parse HEAD`): 3b15763d5220ff733571e678b4cc69d341a1fed5
