### ISSUE TITLE
`shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId` (`RequestingNewTokenTest`) failing with "Timed out waiting for 30000 ms"

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#846]
I've only seen one failure so far for this test, but am creating an issue so we can track it.

Failing from our Android emulation workflow. This link will only survive as long as GitHub keeps the test run logs, so I'll also quote from the output...

[At API Level 27](https://github.com/ably/ably-asset-tracking-android/actions/runs/3685230365/jobs/6235939201#step:4:783) (https://github.com/ably/ably-asset-tracking-android/pull/843):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId[test(AVD) - 8.1.0] FAILED 
	kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)

[ddms]: Exception during activity from Selector.
[ddms]: null
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
	at java.base/java.nio.channels.SelectionKey.isAcceptable(SelectionKey.java:425)
	at com.android.ddmlib.internal.jdwp.JdwpProxyServer.runAsServer(JdwpProxyServer.java:281)
	at com.android.ddmlib.internal.jdwp.JdwpProxyServer.run(JdwpProxyServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by QuintinWillison** [comment]
Probably related, I've seen `shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId` from this same test suite also fail:

[At API Level 24](https://github.com/ably/ably-asset-tracking-android/actions/runs/3693590988/jobs/6253753993#step:4:668):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId[test(AVD) - 7.0] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
Tests on test(AVD) - 7.0 failed: There was 1 failure(s).
```

**Comment by QuintinWillison** [comment]
And [at API Level 27](https://github.com/ably/ably-asset-tracking-android/actions/runs/3695400140/jobs/6258033517#step:4:758) (https://github.com/ably/ably-asset-tracking-android/pull/848):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId[test(AVD) - 8.1.0] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
```

**Comment by QuintinWillison** [comment]
Again, perhaps different but same test, [at API Level 27](https://github.com/ably/ably-asset-tracking-android/actions/runs/3695808453/jobs/6261651108#step:4:698) (https://github.com/ably/ably-asset-tracking-android/pull/850):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId[test(AVD) - 8.1.0] FAILED 
	kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
```

**Comment by QuintinWillison** [comment]
[At API Level 27](https://github.com/ably/ably-asset-tracking-android/actions/runs/3716720723/jobs/6303356951#step:4:706) (https://github.com/ably/ably-asset-tracking-android/pull/855):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId[test(AVD) - 8.1.0] FAILED 
	kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
```

**Comment by QuintinWillison** [comment]
[At API Level 29](https://github.com/ably/ably-asset-tracking-android/actions/runs/3758334740/jobs/6386550097#step:4:656) (https://github.com/ably/ably-asset-tracking-android/pull/856):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldNotAddTrackableWhenRenewedTokenDoesNotHaveCapabilityForTrackableId[test(AVD) - 10] FAILED 
	kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
```

**Comment by AndyTWF** [comment]
I had a little look at this to see if I could get a local reproduction for the 30000ms error, I did manage to do so when my emulators internet failed:

The steps:

- Run the test
- An exception is thrown, as a result of a timeout whilst connecting to Ably (as my emulators internet was broken)
- Execution enters publisher.stop()
- Hangs there for 30s then test fails with exception

**Comment by AndyTWF** [comment]
Another way the test could be improved that I noticed whilst I was investigating the above: if an Exception is thrown for any other reason, the test can return a false-positive result.

A possible fix would be to catch the specific type of exception we expect for the purpose of this test, or pick some information out of the exception message to ensure that it's the correct one (in my case, with emulator Wifi just turned off, the test passed quickly because it couldn't connect to Ably).

**Comment by QuintinWillison** [comment]
As [previously noted](https://github.com/ably/ably-asset-tracking-android/issues/846#issuecomment-1350929583) there is a possible related failure in `shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId ` as seen  [here](https://github.com/ably/ably-asset-tracking-android/actions/runs/3911391072/jobs/6684729774#step:4:727) (https://github.com/ably/ably-asset-tracking-android/pull/866):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
```

A bit more detail from the build report for `publishing-sdk`:

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.ably.tracking.publisher.RequestingNewTokenTest.shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId(RequestingNewTokenTest.kt:47)
```

**Comment by QuintinWillison** [comment]
[At API Level 27](https://github.com/ably/ably-asset-tracking-android/actions/runs/3938241117/jobs/6737061911#step:4:793) (https://github.com/ably/ably-asset-tracking-android/pull/917, at https://github.com/ably/ably-asset-tracking-android/pull/917/commits/31ded369952368cfaa816f7a175002177c0d4053):

```
com.ably.tracking.publisher.RequestingNewTokenTest > shouldAddTrackableWhenRenewedTokenHasCapabilityForTrackableId[test(AVD) - 8.1.0] FAILED 
	android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=test-notification-channel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
```

With a little bit more information from the build report:

```
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=test-notification-channel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by AndyTWF** [comment]
The above issue from Quintin is something that I experienced during local testing when trying to use Android API 33 - when I googled it was something along the lines of needing to create a channel for the notification
