### ISSUE TITLE
`Publisher.remove()` fails during several connectivity faults

### ISSUE THREAD

**Issue by jaley** [ably/ably-asset-tracking-android#905]
Relates to #871, being largely addressed on #883, but adding a new ticket as there are a couple of separate underlying causes that can manifest as the same `ConnectionException` throwing from `remove()`:

## faultDuringTracking[TcpConnectionRefused]

Connection gets interrupted with two trackables in Online state. Both trackables move to the Offline state as expected.
`faultDuringTracking[TcpConnectionRefused]` then attempts to remove that second trackable. This eventually fails because
`DefaultAbly.leavePresence$onError` is called when the presence leave operation times out.

```
01-13 15:10:14.550 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:10:14.548: [AblyConnectionStateChangeWorker] Ably connection state changed OFFLINE
01-13 15:10:14.552 19291 19319 D PUBLISHING SDK IT: 19007:  13-01-23 15:10:14.551: [DefaultPublisher] Publisher remove operation started
01-13 15:10:14.554 19291 19766 D PUBLISHING SDK IT: THREAD 19245 is 'WebSocketConnectReadThread-19245' [no Looper]
01-13 15:10:14.554 19291 19766 D PUBLISHING SDK IT: 19245:  Connection error  java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 49834): connect failed: ECONNREFUSED (Connection refused)
01-13 15:10:14.667 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:10:14.665: [AblyConnectionStateChangeWorker] Ably connection state changed OFFLINE

01-13 15:10:44.828 19291 19798 D PUBLISHING SDK IT: 19249:  Connection error  java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 43456): connect failed: ECONNREFUSED (Connection refused)

(for 2 mins)

01-13 15:12:15.896 19291 19723 D PUBLISHING SDK IT: 19219:  13-01-23 15:12:15.894: [DefaultAbly] Failed to leave presence for channel tracking:6950bb58-3d79-4cf9-bf9e-f70649923b86 com.ably.tracking.ConnectionException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 44444): connect failed: ECONNREFUSED (Connection refused)
01-13 15:12:15.898 19291 19422 D PUBLISHING SDK IT: 19057:  13-01-23 15:12:15.897: [DefaultAbly] Failed to disconnect for trackable 6950bb58-3d79-4cf9-bf9e-f70649923b86 com.ably.tracking.ConnectionException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 44444): connect failed: ECONNREFUSED (Connection refused)
01-13 15:12:15.899 19291 19422 D PUBLISHING SDK IT: 19057:  13-01-23 15:12:15.898: [DefaultAbly] Failed to disconnect for trackable 6950bb58-3d79-4cf9-bf9e-f70649923b86 com.ably.tracking.ConnectionException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 44444): connect failed: ECONNREFUSED (Connection refused)
01-13 15:12:15.900 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:15.899: [ChannelConnectionStateChangeWorker] Trackable 34239018-e7fe-468e-95d9-4219e005f237 connection state changed OFFLINE
01-13 15:12:15.901 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:15.900: [ChannelConnectionStateChangeWorker] Trackable 6950bb58-3d79-4cf9-bf9e-f70649923b86 connection state changed OFFLINE
01-13 15:12:15.903 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:12:15.902: [DefaultPublisher] Publisher remove operation failed com.ably.tracking.ConnectionException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 44444): connect failed: ECONNREFUSED (Connection refused)


01-13 15:12:25.978 19291 19319 E TestRunner: com.ably.tracking.ConnectionException: failed to connect to localhost/127.0.0.1 (port 13579) from /:: (port 44444): connect failed: ECONNREFUSED (Connection refused)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:61)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at com.ably.tracking.common.DefaultAbly$leavePresence$2$1.onError(Ably.kt:478)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager.failQueuedMessages(ConnectionManager.java:1607)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager.access$100(ConnectionManager.java:38)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager$State.enact(ConnectionManager.java:168)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager$StateChangeAction.enactState(ConnectionManager.java:562)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager$SynchronousStateChangeAction.run(ConnectionManager.java:585)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at io.ably.lib.transport.ConnectionManager$ActionHandler.run(ConnectionManager.java:716)
01-13 15:12:25.978 19291 19319 E TestRunner: 	at java.lang.Thread.run(Thread.java:1012)
```

## faultDuringTracking[TcpConnectionUnresponsive]

AAT seems to correctly move the Trackables to the Offline state during unresponsive TCP connection.
The test then attempts to remove a Trackable. This fails, similarly to `faultDuringTracking[TcpConnectionRefused]`,
except the error this time is a timeout on `channel.attach()`, which seems surprising during a `remove()` call?

```
01-13 15:14:36.306 19291 19319 D PUBLISHING SDK IT: 19007:  13-01-23 15:14:36.305: [DefaultPublisher] Publisher remove operation started
01-13 15:14:36.311 19291 19427 D PUBLISHING SDK IT: 19061:  13-01-23 15:14:36.310: [DefaultAbly] Trying to perform an operation on a suspended channel tracking:5b65c18a-ea1e-4979-8fec-9beee771612d, waiting for the channel to be reconnected

...

01-13 15:14:46.317 19291 19427 D PUBLISHING SDK IT: 19061:  13-01-23 15:14:46.315: [DefaultAbly] Timeout while waiting for channel reconnection tracking:5b65c18a-ea1e-4979-8fec-9beee771612d com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
01-13 15:14:46.321 19291 19427 D PUBLISHING SDK IT: 19061:  13-01-23 15:14:46.318: [DefaultAbly] Failed to disconnect for trackable 5b65c18a-ea1e-4979-8fec-9beee771612d com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
01-13 15:14:46.324 19291 19427 D PUBLISHING SDK IT: 19061:  13-01-23 15:14:46.321: [DefaultAbly] Failed to disconnect for trackable 5b65c18a-ea1e-4979-8fec-9beee771612d com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
01-13 15:14:46.327 19291 19398 D PUBLISHING SDK IT: 19040:  13-01-23 15:14:46.325: [DefaultPublisher] Publisher remove operation failed com.ably.tracking.ConnectionException: Timeout was thrown when waiting for channel to attach
```

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-3243

**Comment by KacperKluka** [comment]
As decided in https://github.com/ably/ably-asset-tracking-android/issues/927 the correct behaviour for the `remove()` should be:

* Presence `leave()`
  * Give leave a total 30s time limit to complete successfully
  * If you get a, `onError` callback within that 30 seconds, check the error code:
    * If it's a `5xx`, schedule a retry in 15 seconds (this doesn't restart overall timeout)
    * If it's a`4xx`, give up, detach and disconnect if final trackable
  * If 30s expire, give up, detach and disconnect if final trackable

* `Publisher.remove()`
  * Triggers presence leave, channel detach, disconnect if final trackable
  * Should return immediately and let the channel/presence cleanup and retry behaviours above happen in background
  * `StateFlow<TrackableState>` change should also be immediate
