### ISSUE TITLE
Flakey test: faultBeforeAddingTrackable[DisconnectWithFailedResume]

### ISSUE THREAD

**Issue by AndyTWF** [ably/ably-asset-tracking-android#961]
```
java.lang.AssertionError: [fault active] publisher.track() did not result in success.
at com.ably.tracking.publisher.PublisherMonitor$waitForStateTransition$1.invokeSuspend(NetworkConnectivityTests.kt:698)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at com.ably.tracking.publisher.PublisherMonitor.waitForStateTransition(NetworkConnectivityTests.kt:683)
at com.ably.tracking.publisher.NetworkConnectivityTests$faultBeforeAddingTrackable$1.invoke(NetworkConnectivityTests.kt:146)
at com.ably.tracking.publisher.NetworkConnectivityTests$faultBeforeAddingTrackable$1.invoke(NetworkConnectivityTests.kt:136)
at com.ably.tracking.publisher.NetworkConnectivityTests.withResources(NetworkConnectivityTests.kt:322)
at com.ably.tracking.publisher.NetworkConnectivityTests.faultBeforeAddingTrackable(NetworkConnectivityTests.kt:136)
... 40 trimmed
Caused by: com.ably.tracking.ConnectionException: Attach timed out for channel tracking:00925c79-2425-4e73-a6ad-feadce77674d
at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:61)
at com.ably.tracking.common.DefaultAbly$enterPresenceSuspending$2$1.onError(Ably.kt:924)
at io.ably.lib.realtime.Presence.failQueuedMessages(Presence.java:896)
at io.ably.lib.realtime.Presence.setSuspended(Presence.java:948)
at io.ably.lib.realtime.ChannelBase.setSuspended(ChannelBase.java:625)
at io.ably.lib.realtime.ChannelBase$2.run(ChannelBase.java:468)
at java.util.TimerThread.mainLoop(Timer.java:562)
at java.util.TimerThread.run(Timer.java:512)
```

Possibly a race condition in ably-java - causing the connection state to go from disconnected -> connected without actually connecting.

**Comment by AndyTWF** [comment]
Confirmed related to an ably-java issue, opened in https://github.com/ably/ably-java/issues/907
